<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/help/localization/en_US.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail elFinder plugin            |
 | Copyright 2014 -  Puzzle <puzzl1536@gmail.com>                        |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['elfinder'] = 'File Manager';
$labels['save'] = 'Save file (elFinder)';
$labels['save_all'] = 'Save attachments (elFinder)';
$labels['save_msg'] = 'Save message(s) (elFinder)';

$messages = array();
$messages['wait_save'] = 'Saving file(s) (elFinder) ...';
$messages['wait_load'] = 'Loading file(s) (elFinder) ...';

?>
