<?php

/*
/*
 +-----------------------------------------------------------------------+
 | plugins/help/localization/fr_FR.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail elFinder plugin            |
 | Copyright 2014 -  Puzzle <puzzl1536@gmail.com>                        |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['elfinder'] = 'Gestionnaire de Fichier';
$labels['save'] = 'Enrgistrer le fichier (elFinder)';
$labels['save_all'] = 'Enregistrer les pièces jointes (elFinder)';
$labels['save_msg'] = 'Enregistrer le(s) message(s) (elFinder)';

$messages = array();
$messages['wait_save'] = 'Enregistrement des fichier(s) (elFinder) ...';
$messages['wait_load'] = 'Chargement des fichier(s) (elFinder) ...';

?>
